<?php
/**
 * @file
 * 
 */

/**
 * Implements hook_menu().
 *
 * These menu callbacks are used to handle non-ajax callbacks on the reservation
 * update/delete buttons and simple redirects the users to the forms normal
 * displayed in the ding_popup's.
 *
 * The id's is url_encoded in the last wildcard parameter.
 */
function ding_custom_reservation_menu() {
  $items = array();

  $items['admin/config/ding/customreservation'] = [
    'title' => 'Ding custom reservation Settings',
    'description' => 'Manage custom reservations module',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ding_custom_reservation_admin_form'],
    'access arguments' => ['administer site configuration'],
    'file' => 'includes/ding_custom_reservation.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['ting/object/%ting_object/customreserve'] = array(
    'page callback' => 'ding_custom_reservation_reserve_ajax',
    'page arguments' => array(2),
    'delivery callback' => 'ajax_deliver',
    'access arguments' => array('perform reservation'),
  );

  return $items;
}

function ding_custom_reservation_form_ding_reservation_reserve_form_alter(&$form, &$form_state, $reservable, $hide_options = FALSE) {
  file_put_contents("/var/www/drupalvm/drupal/web/debug/res3.txt", print_r($form , TRUE), FILE_APPEND);
  if (isset($form['provider_options'])) {
    if (isset($form['provider_options']['fbs_preferred_branch'])) {
      unset ($form['provider_options']['fbs_preferred_branch']);
    }
    if (isset($form['provider_options']['interest_period'])) {
      $form['provider_options']['interest_period']['#options'] = ding_custom_reservation_interest_periods();
    }
  }
  file_put_contents("/var/www/drupalvm/drupal/web/debug/res7.txt", print_r(variable_get('ding_custom_reservations_interest_period'), TRUE), FILE_APPEND);
  variable_del('ding_custom_reservations_interest_period');
  file_put_contents("/var/www/drupalvm/drupal/web/debug/res6.txt", print_r(variable_get('ding_custom_reservations_interest_period'), TRUE), FILE_APPEND);
}


/**
 * Implements hook_ding_entity_buttons().
 */
function ding_custom_reservation_ding_entity_buttons($type, $entity, $view_mode, $widget = 'default') {
  $interest_periods = ding_custom_reservation_interest_periods();
  file_put_contents("/var/www/drupalvm/drupal/web/debug/res5.txt", print_r($interest_periods, TRUE), FILE_APPEND);
  $button = '';

  if ($type == 'ding_entity' && $entity->is('library_material')) {
    switch ($widget) {
      case 'ajax':
        // The AJAX-widget will use AJAX-request for checking reservability and
        // also when performing the reservation.
        $button = array(
          array(
            '#theme' => 'link',
            '#text' => t('Reserve2'),
            '#path' => 'ting/object/' . $entity->id . '/customreserve',
            '#options' => array(
              'attributes' => array(
                'class' => array(
                  'action-button',
                  'reserve-button',
                  'use-ajax',
                  'js-check-reservability',
                ),
                'data-local-id' => $entity->localId,
              ),
              'html' => FALSE,
            ),
            '#attached' => array(
              'js' => array(
                array(
                  'type' => 'file',
                  'data' => drupal_get_path('module', 'ding_reservation') . '/js/ding_reservation_reservability.js',
                ),
              ),
              'library' => array(
                array('system', 'drupal.ajax'),
              ),
            ),
          ),
        );
        break;

      default:
        // The last parameter to the form below (TRUE) hides the provider
        // options in the form (interest period and branch).
        $reservable = ding_provider_invoke('reservation', 'is_reservable', [$entity->localId]);
        if (!empty($reservable[$entity->localId])) {
          $button = array(
            ding_provider_get_form('ding_reservation_reserve_form', new DingReservationReservableEntity($entity), TRUE),
          );
        }
        break;
    }
  }

  return $button;
}

/**
 * Ajax entry callback.
 *
 * Try to reserve the material, if the user is not logged in trigger a ajax
 * login.
 *
 * @param TingEntity $entity
 *   Ting entity object.
 * @param DingReservationReservable $reservable
 *   Object with information about the entity to reserve. Used to make
 *   reservation of periodical, where volume and issue is part of the
 *   reservation.
 *
 * @return array
 *   Render array with Ajax commands.
 */
function ding_custom_reservation_reserve_ajax($entity, $reservable = NULL) {
  file_put_contents("/var/www/drupalvm/drupal/web/debug/res2.txt", print_r($entity , TRUE), FILE_APPEND);
  $commands = array();

  // Check if the logged in user is a library user.
  global $user;
  if (!user_is_logged_in()) {
    // Trigger log-in (the reservation link will be triggered on success).
    $commands[] = ajax_command_ding_user_authenticate('');
  }
  elseif (!ding_user_is_provider_user($user)) {
    // Error not library user.
    $commands[] = ajax_command_ding_popup('ding_reservation', t('Error'), '<p>' . t('Only library user can make reservations.') . '</p>');
  }
  elseif (!(is_object($entity) && $entity instanceof TingEntity)) {
    // Error not ting entity.
    $commands[] = ajax_command_ding_popup('ding_reservation', t('Error'), '<p>' . t('Unable to load information about the material.') . '</p>');
  }
  else {
    // Check if reservable object was paste.
    if (is_null($reservable)) {
      // If no object passed assume "normal" reservation (not periodical).
      $reservable = new DingReservationReservableEntity($entity);
    }

    // Try to make reservation.
    try {
      $form = ding_provider_get_form('ding_reservation_reserve_form', $reservable, FALSE);
      $commands[] = ajax_command_ding_popup('ding_reservation', t('Reservation'), render($form));
    }
    catch (DingProviderAuthException $exception) {
      // The form may have thrown an Auth exception, so display login. (the
      // reservation link will be triggered on success).
      $commands[] = ajax_command_ding_user_authenticate('');
    }
    catch (Exception $exception) {
      // The form may have thrown an auth exception as the login may have
      // timed-out (the reservation link will be triggered on success).
      $commands[] = ajax_command_ding_popup('ding_reservation', t('Error'), '<p>' . t('Unknown error in reservation, please contact the library.') . '</p>');

      // Log exception.
      watchdog_exception('ding_reservation', $exception);
    }
  }

  // Return the ajax commands as an render array.
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Reserve form validation.
 */
function ding_custom_reservation_reserve_form_validate($form, &$form_state) {
  global $user;
  if (!(user_is_logged_in() && ding_user_is_provider_user($user))) {
    throw new DingProviderAuthException();
  }
}

/**
 * Default values for interest period.
 */
function ding_custom_reservation_default_interest_periods() {
  $periods = [
    1 => 30,
    2 => 60,
    3 => 90,
    6 => 180,
    12 => 360,
  ];
  $options = [];
  foreach ($periods as $months => $days) {
    $options[$days] = format_plural($months, '1 month', '@count months');
  }
  return $options;
}

/**
 * Get interest periods.
 *
 * @return array
 *   Array of days => human readable string.
 */
function ding_custom_reservation_interest_periods() {
  return variable_get('ding_custom_reservation_interest_periods', ding_custom_reservation_default_interest_periods());
}